# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

# Azure DevOps repository operations for propagate_updates.ps1
# Uses global: $azure_work_item

# Source dependencies
. "$PSScriptRoot\status_tracking.ps1"
. "$PSScriptRoot\watch_azure_pr.ps1"

# get Azure DevOps organization and project from git remote URL
function get-azure-org-project {
    param(
        [string] $repo_name
    )
    $result = $null

    Push-Location $repo_name
    $repo_url = git config --get remote.origin.url
    Pop-Location

    # Parse URL like https://msazure@dev.azure.com/msazure/One/_git/repo-name
    # or https://dev.azure.com/msazure/One/_git/repo-name
    if($repo_url -match "dev\.azure\.com/([^/]+)/([^/]+)/_git") {
        $org = $matches[1]
        $project = $matches[2]
        $result = @{
            Organization = "https://dev.azure.com/$org"
            Project = $project
        }
    }
    # Parse URL like https://msazure.visualstudio.com/DefaultCollection/One/_git/repo-name
    # or https://msazure.visualstudio.com/One/_git/repo-name
    elseif($repo_url -match "([^/]+)\.visualstudio\.com/(?:DefaultCollection/)?([^/]+)/_git") {
        $org = $matches[1]
        $project = $matches[2]
        $result = @{
            Organization = "https://dev.azure.com/$org"
            Project = $project
        }
    }
    else {
        fail-with-status "Failed to parse Azure DevOps organization and project from remote URL: $repo_url"
    }

    return $result
}


# create PR to update dependencies for Azure repo using Azure CLI
function create-pr-azure {
    param(
        [string] $repo_name,
        [string] $new_branch_name
    )
    $result = $null

    Write-Host "`nCreating PR"

    $azure_info = get-azure-org-project $repo_name
    $org = $azure_info.Organization
    $project = $azure_info.Project

    $pr_output = az repos pr create `
        --repository $repo_name `
        --source-branch $new_branch_name `
        --target-branch master `
        --title "[autogenerated] update dependencies" `
        --description "Propagating dependency updates" `
        --organization $org `
        --project $project `
        --output json

    if($LASTEXITCODE -ne 0) {
        fail-with-status "Failed to create PR for repo $repo_name"
    }
    else {
        Write-Host "PR created successfully" -ForegroundColor Green
        $result = $pr_output | ConvertFrom-Json
    }

    return $result
}


# link work item to PR for Azure repo using Azure CLI
function link-work-item-to-pr-azure {
    param(
        [int] $pr_id,
        [string] $org,
        [string] $project
    )

    Write-Host "Linking work item to PR (PR ID: $pr_id)"

    if(!$azure_work_item){
        fail-with-status "Updating Azure repos requires providing a work item id. Provide work item id as: -azure_work_item [id]"
    }
    else {
        $output = az repos pr work-item add `
            --id $pr_id `
            --work-items $azure_work_item `
            --organization $org `
            --output json

        if($LASTEXITCODE -ne 0) {
            fail-with-status "Failed to link work item to PR. Work item: $azure_work_item, PR ID: $pr_id"
        }
        else {
            Write-Host "Work item linked successfully" -ForegroundColor Green
        }
    }
}


# approve PR for Azure repo using Azure CLI
function approve-pr-azure {
    param(
        [int] $pr_id,
        [string] $org
    )

    Write-Host "Approving PR"

    $output = az repos pr set-vote `
        --id $pr_id `
        --vote approve `
        --organization $org `
        --output json

    if($LASTEXITCODE -ne 0) {
        fail-with-status "Failed to approve PR ID: $pr_id"
    }
    else {
        Write-Host "PR approved successfully" -ForegroundColor Green
    }
}


# set PR for Azure repo to merge automatically once build completes using Azure CLI
function set-autocomplete-azure {
    param(
        [int] $pr_id,
        [string] $org
    )

    Write-Host "Enabling PR to autocomplete"

    $output = az repos pr update `
        --id $pr_id `
        --auto-complete true `
        --squash true `
        --delete-source-branch true `
        --organization $org `
        --output json

    if($LASTEXITCODE -ne 0) {
        fail-with-status "Failed to set autocomplete for PR ID: $pr_id"
    }
    else {
        Write-Host "Autocomplete enabled successfully" -ForegroundColor Green
    }
}


# wait until build completes for Azure repo using Azure CLI
function wait-until-complete-azure {
    param(
        [int] $pr_id,
        [string] $org,
        [string] $repo_name
    )
    $done = $false

    Write-Host "Waiting for build to complete"
    Write-Host "`nWatching PR policies..."
    $success = watch-azure-pr-policies -pr_id $pr_id -org $org -poll_interval 30 -timeout 120 -ShowBuildDetails -OnIteration { show-propagation-status }

    if(!$success) {
        # Check if PR completed despite policy failures (e.g., manually merged)
        $pr_output = az repos pr show --id $pr_id --organization $org --output json
        if($LASTEXITCODE -eq 0) {
            $pr_info = $pr_output | ConvertFrom-Json
            if($pr_info.status -eq "completed") {
                Write-Host "PR completed successfully" -ForegroundColor Green
                $done = $true
            }
            else {
                # PR not completed, fall through to fail
            }
        }
        else {
            # couldn't get PR status, fall through to fail
        }
        if(!$done) {
            fail-with-status "PR $pr_id failed to complete. Check policy status above."
        }
        else {
            # already done
        }
    }
    else {
        # Verify PR is completed
        $pr_output = az repos pr show --id $pr_id --organization $org --output json
        if($LASTEXITCODE -ne 0) {
            fail-with-status "Failed to get PR status for ID: $pr_id"
        }
        else {
            $pr_info = $pr_output | ConvertFrom-Json
            if($pr_info.status -ne "completed") {
                # PR policies passed but PR not yet merged - wait a bit for autocomplete
                Write-Host "Waiting for PR to auto-complete..."
                $max_wait = 60
                $waited = 0
                while($waited -lt $max_wait -and !$done) {
                    Start-Sleep -Seconds 10
                    $waited += 10
                    $pr_output = az repos pr show --id $pr_id --organization $org --output json
                    $pr_info = $pr_output | ConvertFrom-Json
                    if($pr_info.status -eq "completed") {
                        Write-Host "PR completed successfully" -ForegroundColor Green
                        $done = $true
                    }
                    else {
                        # keep waiting
                    }
                }
                if(!$done) {
                    Write-Host "Warning: PR policies passed but PR status is: $($pr_info.status)" -ForegroundColor Yellow
                }
                else {
                    # already logged success
                }
            }
            else {
                Write-Host "PR completed successfully" -ForegroundColor Green
            }
        }
    }
}


# update dependencies for Azure repo using Azure CLI
function update-repo-azure {
    param(
        [string] $repo_name,
        [string] $new_branch_name
    )

    $azure_info = get-azure-org-project $repo_name
    $org = $azure_info.Organization
    $project = $azure_info.Project

    $pr_info = create-pr-azure $repo_name $new_branch_name
    $pr_id = $pr_info.pullRequestId

    link-work-item-to-pr-azure $pr_id $org $project

    approve-pr-azure $pr_id $org

    set-autocomplete-azure $pr_id $org

    wait-until-complete-azure $pr_id $org $repo_name
}
