# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

# GitHub repository operations for propagate_updates.ps1

# Source dependencies
. "$PSScriptRoot\status_tracking.ps1"
. "$PSScriptRoot\watch_github_pr.ps1"

# update dependencies for Github repo
# Returns the PR URL for status tracking
function update-repo-github
{
    param(
        [string] $repo_name,
        [string] $new_branch_name,
        [hashtable] $description
    )
    $fn_result = $null

    Push-Location $repo_name
    Write-Host "`nCreating PR"
    $working_directory = (Get-Location).Path

    $pr_title = "[autogenerated] update dependencies"
    $pr_body = "Propagating dependency updates"
    if ($description)
    {
        $pr_title = $description.PrTitle
        $pr_body = $description.PrBody
    }
    else
    {
        # no description, use defaults
    }

    $create_output = gh pr create --title $pr_title --body $pr_body --head $new_branch_name 2>&1
    if ($LASTEXITCODE -ne 0)
    {
        Write-Host "PR creation returned error (may already exist), checking..." -ForegroundColor Yellow
    }
    else
    {
        Write-Host "PR created" -ForegroundColor Green
    }

    # Get PR URL
    $pr_info = gh pr view --json url 2>&1
    if($LASTEXITCODE -eq 0)
    {
        $pr_data = $pr_info | ConvertFrom-Json
        $fn_result = $pr_data.url
    }
    else
    {
        # couldn't get PR URL
    }

    # Update status with PR URL immediately so it shows even if later steps fail
    set-repo-status -repo_name $repo_name -status $script:STATUS_IN_PROGRESS -pr_url $fn_result

    # Enable auto-merge so GitHub merges once required checks pass
    Write-Host "Enabling auto-merge"
    $null = gh pr merge --auto --squash --delete-branch 2>&1
    if($LASTEXITCODE -ne 0)
    {
        Write-Host "Warning: Could not enable auto-merge, will merge manually" -ForegroundColor Yellow
    }
    else
    {
        Write-Host "Auto-merge enabled" -ForegroundColor Green
    }

    # Post pipeline trigger immediately - polling will detect when checks start
    Write-Host "Triggering pipeline..." -ForegroundColor Cyan
    $null = gh pr comment --body "/AzurePipelines run"

    # Poll until CI checks appear (not just CLA/license checks which are always present)
    Write-Host "Waiting for CI checks to start... (Press Ctrl+C to cancel)" -ForegroundColor Gray
    $max_wait = 180
    $waited = 0
    $checks_started = $false
    while ($waited -lt $max_wait -and -not $checks_started)
    {
        $cancelled = wait-or-cancel -seconds 5
        if ($cancelled) { $global:propagation_cancelled = $true; return $pr_url }
        $waited += 5
        $checks_output = gh pr checks --json name,state 2>&1
        if ($LASTEXITCODE -eq 0 -and $checks_output -ne "[]" -and $checks_output -ne "")
        {
            $checks = $checks_output | ConvertFrom-Json
            # Filter out license/CLA checks — wait for actual CI checks
            $ci_checks = @($checks | Where-Object { $_.name -notmatch "license|cla" })
            if ($ci_checks.Count -gt 0)
            {
                $checks_started = $true
                Write-Host "CI checks detected after ${waited}s ($($ci_checks.Count) check(s))" -ForegroundColor Green
            }
            else
            {
                # only CLA/license checks so far, keep waiting
            }
        }
        else
        {
            # checks not yet visible, keep polling
        }
    }
    if (-not $checks_started)
    {
        Write-Host "No checks detected after ${max_wait}s, proceeding to watch anyway" -ForegroundColor Yellow
    }
    else
    {
        # checks started
    }

    Write-Host "Waiting for build to complete"
    $watch_result = watch-github-pr-checks -poll_interval $global:poll_interval -timeout 120 -OnIteration { [void](show-propagation-status) }

    # Check if PR was auto-merged
    $pr_state = gh pr view --json state 2>&1
    $merged = $false
    if($LASTEXITCODE -eq 0)
    {
        $state_data = $pr_state | ConvertFrom-Json
        if($state_data.state -eq "MERGED")
        {
            $merged = $true
            Write-Host "PR auto-merged successfully" -ForegroundColor Green
        }
        else
        {
            # PR not merged yet
        }
    }
    else
    {
        # couldn't get PR state
    }

    if(-not $merged)
    {
        # Auto-merge didn't happen — required checks may have failed
        if(-not $watch_result.Success)
        {
            fail-with-status "PR checks failed for repo ${repo_name}: $($watch_result.Message)"
        }
        else
        {
            # Checks passed but auto-merge hasn't triggered yet, wait and retry
            Write-Host "Waiting for auto-merge to complete..."
            $max_wait = 120
            $waited = 0
            while($waited -lt $max_wait -and -not $merged)
            {
                $cancelled = wait-or-cancel -seconds 2
                if ($cancelled) { $global:propagation_cancelled = $true; break }
                $waited += 2
                $pr_state = gh pr view --json state 2>&1
                if($LASTEXITCODE -eq 0)
                {
                    $state_data = $pr_state | ConvertFrom-Json
                    if($state_data.state -eq "MERGED")
                    {
                        $merged = $true
                        Write-Host "PR auto-merged successfully" -ForegroundColor Green
                    }
                    else
                    {
                        # still waiting
                    }
                }
                else
                {
                    # couldn't get PR state
                }
            }

            if(-not $merged)
            {
                fail-with-status "PR for repo $repo_name was not merged after waiting ${max_wait}s"
            }
            else
            {
                # already logged success
            }
        }
    }
    else
    {
        # already merged
    }

    # Wait for merge to settle
    Start-Sleep -Seconds 2
    Pop-Location

    return $fn_result
}
