# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

# GitHub repository operations for propagate_updates.ps1

# Source dependencies
. "$PSScriptRoot\status_tracking.ps1"
. "$PSScriptRoot\watch_github_pr.ps1"

# update dependencies for Github repo
function update-repo-github {
    param(
        [string] $repo_name,
        [string] $new_branch_name
    )
    Push-Location $repo_name
    Write-Host "`nCreating PR"
    $working_directory = (Get-Location).Path
    gh pr create --title "[autogenerated] update dependencies" --body "Propagating dependency updates" --head $new_branch_name
    gh pr comment --body "/AzurePipelines run"
    Write-Host "Waiting for checks to start"
    Start-Sleep -Seconds 120

    Write-Host "Waiting for build to complete"
    $result = watch-github-pr-checks -poll_interval 30 -timeout 120 -OnIteration { show-propagation-status }
    if(-not $result.Success) {
        fail-with-status "PR checks failed for repo ${repo_name}: $($result.Message)"
    }
    else {
        Write-Host "PR checks passed" -ForegroundColor Green
    }

    Write-Host "Merging PR"
    gh pr merge --squash --delete-branch
    if($LASTEXITCODE -ne 0) {
        fail-with-status "Failed to merge PR for repo $repo_name"
    }
    else {
        Write-Host "PR merged successfully" -ForegroundColor Green
    }
    # Wait for merge to complete
    Start-Sleep -Seconds 10
    Pop-Location
}
