# This is the job template for building the binaries for one configuration. It does:
# - setup the machine
# - build binaries for desired configuration
# - upload binaries artifacts for the desired configuration

parameters:
  - name: BUILD_SUFFIX
    type: string
  - name: GBALLOC_LL_TYPE
    type: string
  - name: FSANITIZE_TYPE
    type: string
  - name: build_configuration
    default: "Debug"
  - name: ARCH_TYPE
    default: "x64"
  - name: cmake_options
    type: string
    default: "-Drun_reals_check:bool=ON -Drun_unittests:bool=ON -Drun_int_tests:bool=ON -Duse_cppunittest:bool=ON -Drun_traceability:BOOL=ON -Drun_repo_validation:BOOL=ON"
  # If this parameter is specified the specified test suite will be run without invoking ctest
  - name: run_test_suite_without_ctest
    type: string
    default: ""
  # Settings to add an app verifier step for ctest
  - name: with_app_verifier
    type: boolean
    default: false
  - name: repo_root_override
    default: $(Build.SourcesDirectory)/deps/c-build-tools
  - name: binary_name_suffix
    default: ".exe"
  - name: appverifier_skip_tests_list
    type: string
    default: ""
  - name: use_cppunittest
    type: boolean
    default: true

jobs:
- job: build_and_run_tests_${{ parameters.BUILD_SUFFIX }}
  displayName: 'Build and run tests, build_configuration: ${{ parameters.build_configuration }}, ${{ parameters.GBALLOC_LL_TYPE}}, ARCH_TYPE=${{ parameters.ARCH_TYPE }}, FSANITIZE_TYPE: ${{ parameters.FSANITIZE_TYPE}}'

  variables:
    ${{ if eq(parameters.FSANITIZE_TYPE, 'ON') }}:
      use_vld_option: '-Duse_vld:bool=OFF'
    ${{ if eq(parameters.FSANITIZE_TYPE, 'OFF') }}:
      use_vld_option: '-Duse_vld:bool=ON'

  pool:
    name: Azure-MessagingStore-WinBuildPoolVS2022_0
    demands:
    - msbuild
    - cmake
    - visualstudio

  workspace:
    clean: all

  steps:
  - checkout: self
    submodules: true
    clean: false

  - task: BatchScript@1
    displayName: 'Git submodule update'
    inputs:
      filename: 'C:\Program Files\Git\bin\git.exe'
      arguments: 'submodule update --init --force'

  - task: BatchScript@1
    displayName: 'Git submodule clean'
    inputs:
      filename: 'C:\Program Files\Git\bin\git.exe'
      arguments: 'submodule foreach --recursive "git clean -xdff"'

  - task: BatchScript@1
    displayName: 'Git clean'
    inputs:
      filename: 'C:\Program Files\Git\bin\git.exe'
      arguments: 'clean -xdff'

  - task: BatchScript@1
    displayName: 'Setup VS Vars'
    inputs:
      filename: '"c:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"'
      modifyEnvironment: true

  # Cleanup appverifier from any previous runs
  - template : disable_appverifier.yml
    parameters:
      ${{ if ne(parameters.repo_root_override, '') }}:
        repo_root: ${{ parameters.repo_root_override }}

  - task: CMake@1
    displayName: '🏗️ CMake $(Build.SourcesDirectory) ${{ parameters.cmake_options }} ${{ variables.use_vld_option }} -DGBALLOC_LL_TYPE:string=${{ parameters.GBALLOC_LL_TYPE }} -DCMAKE_BUILD_TYPE=${{ parameters.build_configuration }} -G "Visual Studio 17 2022" -A ${{ parameters.ARCH_TYPE }}'
    inputs:
      workingDirectory: '$(Build.BinariesDirectory)\c'
      cmakeArgs: '$(Build.SourcesDirectory) ${{ parameters.cmake_options }} ${{ variables.use_vld_option }} -DGBALLOC_LL_TYPE:string=${{ parameters.GBALLOC_LL_TYPE }} -DCMAKE_BUILD_TYPE=${{ parameters.build_configuration }} -G "Visual Studio 17 2022" -A ${{ parameters.ARCH_TYPE }}'

  - task: VSBuild@1
    displayName: '🏗️ Build solution $(Build.BinariesDirectory)\c\*.sln'
    inputs:
      solution: '$(Build.BinariesDirectory)\c\*.sln'
      msbuildArgs: '/t:restore /t:build'
      configuration: ${{ parameters.build_configuration }}
      maximumCpuCount: true

  - template : start_logman.yml

  # in the gate address sanitizer has problems running which are not reproducible locally, so skipping Address Sanitizer for vstest (note: ctest is perfectly fine with Address Sanitizer)
  # here's example:
  #   vstest.console will output
  # Starting test execution, please wait...
  #A total of 257 test files matched the specified pattern.
  ##[error]The active test run was aborted. Reason: Test host process crashed : AddressSanitizer: CHECK failed: asan_thread.cpp:273 "((tid())) == ((0))" (0x1, 0x0) (tid=11016)
  # [continues, with none of our code on any stack]
  - ${{ if and(eq(parameters.FSANITIZE_TYPE, 'OFF'), eq(parameters.run_test_suite_without_ctest, ''), parameters.use_cppunittest) }}:
    - task: VSTest@2
      displayName: '🧪 VsTest - testAssemblies (no int tests)'
      inputs:
        # Some repos do not use BUILD_BINARIESDIRECTORY in cmakelists so the DLLs may be in either of the two paths below
        testAssemblyVer2: |
          $(Build.BinariesDirectory)\c\${{ parameters.build_configuration }}\**\*_ut_*.dll
          $(Build.BinariesDirectory)\${{ parameters.build_configuration }}\**\*_ut_*.dll
        runInParallel: true
        runTestsInIsolation: true
        failOnMinTestsNotRun: true
        codeCoverageEnabled: true # Requires runSettingsFile and collect option below
        platform: 'x64'
        configuration: '${{ parameters.build_configuration }}'
        diagnosticsEnabled : true
        otherConsoleOptions: '/collect:"Code Coverage;Format=Xml"'
        runSettingsFile: '${{ parameters.repo_root_override }}/pipeline_templates/scripts/tests_native.runsettings'
        resultsFolder: '$(build.ArtifactStagingDirectory)/Test/VsTest/Results/${{ parameters.build_configuration }}${{ parameters.BUILD_SUFFIX }}'
        testRunTitle: 'VsTest Native ${{ parameters.build_configuration }}${{ parameters.BUILD_SUFFIX }}'

    # Publish code coverage results from vstest
    - task: PublishCodeCoverageResults@2
      displayName: '📰 Publish Code Coverage'
      inputs:
        summaryFileLocation: '$(build.ArtifactStagingDirectory)/Test/VsTest/Results/${{ parameters.build_configuration }}${{ parameters.BUILD_SUFFIX }}/*/*.xml'
        pathToSources: '$(Build.SourcesDirectory)'

  - ${{ if eq(parameters.run_test_suite_without_ctest, '') }}:
    - task: CmdLine@2
      displayName: '🧪 Run ctest'
      inputs:
        # --interactive-debug-mode 1 is needed to get Watson dumps when running tests under ctest: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9855/diffs?commit_id=0a4ee422c1a5a5f6e9fd8893c5029da446ae8a91#diff-content-073a6620d87def59fe2a133050c1d68204635312
        script: 'ctest -C "${{ parameters.build_configuration }}" --output-on-failure --interactive-debug-mode 1 --no-tests=error --output-junit ctest_results_${{ parameters.build_configuration }}${{ parameters.BUILD_SUFFIX }}.xml'
        workingDirectory: $(Build.BinariesDirectory)\c

  - task: PublishTestResults@2
    displayName: '📊 Publish ctest results'
    inputs:
      testResultsFormat: 'JUnit'
      searchFolder: $(Build.BinariesDirectory)\c
      testResultsFiles: 'ctest_results_${{ parameters.build_configuration }}${{ parameters.BUILD_SUFFIX }}.xml'
      testRunTitle: 'ctest${{ parameters.BUILD_SUFFIX }}'
      buildConfiguration: ${{ parameters.build_configuration }}
      failTaskOnMissingResultsFile: true
    condition: always()

  - ${{ if and(eq(parameters.FSANITIZE_TYPE, 'OFF'), and(eq(parameters.run_test_suite_without_ctest, ''), parameters.with_app_verifier)) }}:
    - template : run_ctests_with_appverifier.yml
      parameters:
        ${{ if ne(parameters.repo_root_override, '') }}:
          repo_root: ${{ parameters.repo_root_override }}
        binary_name_suffix: ${{ parameters.binary_name_suffix }}
        ctest_tests_bin_directory: $(Build.BinariesDirectory)\c
        ${{ if ne(parameters.appverifier_skip_tests_list, '') }}:
          ctest_additional_args: "-E ${{ parameters.appverifier_skip_tests_list }}"
        test_steps:
        - task: CmdLine@2
          displayName: '🧪 Run ctest'
          inputs:
            # --interactive-debug-mode 1 is needed to get Watson dumps when running tests under ctest: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9855/diffs?commit_id=0a4ee422c1a5a5f6e9fd8893c5029da446ae8a91#diff-content-073a6620d87def59fe2a133050c1d68204635312
            ${{ if ne(parameters.appverifier_skip_tests_list, '') }}:
              script: 'ctest -C "${{ parameters.build_configuration }}" --output-on-failure --interactive-debug-mode 1 -E ${{ parameters.appverifier_skip_tests_list }} --output-junit ctest_appverifier_results_${{ parameters.build_configuration }}${{ parameters.BUILD_SUFFIX }}.xml'
            ${{ else }}:
              script: 'ctest -C "${{ parameters.build_configuration }}" --output-on-failure --interactive-debug-mode 1 --no-tests=error --output-junit ctest_appverifier_results_${{ parameters.build_configuration }}${{ parameters.BUILD_SUFFIX }}.xml'
            workingDirectory: $(Build.BinariesDirectory)\c

    - task: PublishTestResults@2
      displayName: '📊 Publish ctest results'
      inputs:
        testResultsFormat: 'JUnit'
        searchFolder: $(Build.BinariesDirectory)\c
        testResultsFiles: 'ctest_appverifier_results_${{ parameters.build_configuration }}${{ parameters.BUILD_SUFFIX }}.xml'
        testRunTitle: 'CTest${{ parameters.BUILD_SUFFIX }} App Verifier'
        buildConfiguration: ${{ parameters.build_configuration }}
        failTaskOnMissingResultsFile: true
      condition: always()

  - ${{ if not(eq(parameters.run_test_suite_without_ctest, '')) }}:
    - task: CmdLine@2
      displayName: '🧪 Run ${{ parameters.run_test_suite_without_ctest }}'
      inputs:
        script: '$(Build.BinariesDirectory)\${{ parameters.build_configuration }}\${{ parameters.run_test_suite_without_ctest }}\${{ parameters.run_test_suite_without_ctest }}.exe'
        workingDirectory: '$(Build.BinariesDirectory)\${{ parameters.build_configuration }}\${{ parameters.run_test_suite_without_ctest }}'

  - template : stop_logman.yml

  - task: PublishPipelineArtifact@1
    displayName: 'Publish ${{ parameters.ARCH_TYPE }} ${{ parameters.build_configuration}} Artifacts'
    inputs:
      targetPath: $(Build.BinariesDirectory)
      artifactName: ${{ parameters.build_configuration}}_${{ parameters.ARCH_TYPE }}_artifacts
      parallel: true
    condition: failed()

  - template : clean_ado_folders.yml
