# verifies that all submodules are ancestors of their master branch

parameters:
  - name: repo_root
    default: $(Build.SourcesDirectory)/deps/c-build-tools
  - name: ignore_submodules # Comma-separated list of submodules to ignore
    default: ""
    type: string

jobs:
- job: run_master_check
  displayName: 'Run submodule master check'
  pool:
    name: Azure-MessagingStore-WinBuildPoolVS2022_0
    demands:
    - Cmd

  workspace:
    clean: all

  steps:
  - checkout: self
    submodules: true
    clean: false

  - task: BatchScript@1
    displayName: 'Git submodule update'
    inputs:
      filename: 'C:\Program Files\Git\bin\git.exe'
      arguments: 'submodule update --init --force'

  - task: BatchScript@1
    displayName: 'Git submodule clean'
    inputs:
      filename: 'C:\Program Files\Git\bin\git.exe'
      arguments: 'submodule foreach --recursive "git clean -xdff"'

  - task: BatchScript@1
    displayName: 'Git clean'
    inputs:
      filename: 'C:\Program Files\Git\bin\git.exe'
      arguments: 'clean -xdff'

  - task: PowerShell@2
    displayName: 'Verify submodules are ancestors of their master branch'
    inputs:
      targetType: 'filePath'
      filePath: '${{ parameters.repo_root }}/pipeline_templates/scripts/submodule_master_check.ps1'
      arguments: '-ignoreSubmodules ${{ parameters.ignore_submodules }}'
    continueOnError: false