# verifies that all submodules are ancestors of their master branch

parameters:
  - name: repo_root
    default: $(Build.SourcesDirectory)/deps/c-build-tools

jobs:
- job: run_master_check
  displayName: 'Run submodule master check'
  pool:
    name: Azure-MessagingStore-WinBuildPoolVS2022_0
    demands:
    - Cmd

  workspace:
    clean: all

  steps:
  - task: PowerShell@2
    displayName: 'Verify submodules are ancestors of their master branch'
    inputs:
      targetType: 'filePath'
      filePath: '${{ parameters.repo_root }}/pipeline_templates/scripts/submodule_master_check.ps1'
    continueOnError: false